package com.coral.epidemicsimapiserver.repository;

import java.util.UUID;

public record CreateGameRequest(int time_step,
        int num_agents,
        double compliance_probability,
        double seeks_treatment_probability,
        double mask_filtration_efficiency_mean,
        double mask_filtration_efficiency_sd,
        double pulmonary_ventilation_rate_mean,
        double pulmonary_ventilation_rate_sd,
        double incubation_period_mean,
        double incubation_period_sd,
        double recovery_period_mean,
        double recovery_period_sd,
        double immunity_period_mean,
        double immunity_period_sd,
        double prehospitalization_period_mean,
        double prehospitalization_period_sd,
        double hospitalization_period_mean,
        double hospitalization_period_sd,
        double quanta_emission_rate_mean,
        double quanta_emission_rate_sd,
        double hospitalization_probability,
        double death_probability,
        double asymptomatic_probability,
        double household_capacity_mean,
        double household_capacity_sd,
        double household_air_change_rate_mean,
        double household_air_change_rate_sd,
        double household_volume_mean,
        double household_volume_sd,
        double office_capacity_mean,
        double office_capacity_sd,
        double office_air_change_rate_mean,
        double office_air_change_rate_sd,
        double office_volume_mean,
        double office_volume_sd,
        double social_space_capacity_mean,
        double social_space_capacity_sd,
        double social_space_air_change_rate_mean,
        double social_space_air_change_rate_sd,
        double social_space_volume_mean,
        double social_space_volume_sd,
        double healthcare_space_capacity_mean,
        double healthcare_space_capacity_sd,
        double healthcare_space_air_change_rate_mean,
        double healthcare_space_air_change_rate_sd,
        double healthcare_space_volume_mean,
        double healthcare_space_volume_sd,
        double test_capacity_mean,
        double test_capacity_sd,
        double test_sensitivity,
        double test_specificity) {

    public CreateGamePacket toCreateGamePacket() {
        CreateGamePacket createGamePacket = new CreateGamePacket(
                UUID.randomUUID().toString(),
                this.time_step,
                this.num_agents,
                this.compliance_probability,
                this.seeks_treatment_probability,
                this.mask_filtration_efficiency_mean,
                this.mask_filtration_efficiency_sd,
                this.pulmonary_ventilation_rate_mean,
                this.pulmonary_ventilation_rate_sd,
                this.incubation_period_mean,
                this.incubation_period_sd,
                this.recovery_period_mean,
                this.recovery_period_sd,
                this.immunity_period_mean,
                this.immunity_period_sd,
                this.prehospitalization_period_mean,
                this.prehospitalization_period_sd,
                this.hospitalization_period_mean,
                this.hospitalization_period_sd,
                this.quanta_emission_rate_mean,
                this.quanta_emission_rate_sd,
                this.hospitalization_probability,
                this.death_probability,
                this.asymptomatic_probability,
                this.household_capacity_mean,
                this.household_capacity_sd,
                this.household_air_change_rate_mean,
                this.household_air_change_rate_sd,
                this.household_volume_mean,
                this.household_volume_sd,
                this.office_capacity_mean,
                this.office_capacity_sd,
                this.office_air_change_rate_mean,
                this.office_air_change_rate_sd,
                this.office_volume_mean,
                this.office_volume_sd,
                this.social_space_capacity_mean,
                this.social_space_capacity_sd,
                this.social_space_air_change_rate_mean,
                this.social_space_air_change_rate_sd,
                this.social_space_volume_mean,
                this.social_space_volume_sd,
                this.healthcare_space_capacity_mean,
                this.healthcare_space_capacity_sd,
                this.healthcare_space_air_change_rate_mean,
                this.healthcare_space_air_change_rate_sd,
                this.healthcare_space_volume_mean,
                this.healthcare_space_volume_sd,
                this.test_capacity_mean,
                this.test_capacity_sd,
                this.test_sensitivity,
                this.test_specificity

        );

        return createGamePacket;
    }
}
